### ISSUE TITLE
Updating links & title

### ISSUE THREAD

**Issue by jenna-jordan** [carpentries-incubator/python-interactive-data-visualizations#1]
@tobyhodges I would like to update the name of the repo (from "data-visualization-workshop" to "python-interactive-data-visualizations"), as well as to fix the description and link. I notice that I do not have access to the "Settings" tab for this repository, or I would go ahead and do this myself. Is this a result of the migration not being finished?

**Comment by tobyhodges** [comment]
Hi @jenna-jordan when the transfer is first done, you are only given _Write_ access to the repository by default. I have now updated that to give you full _Admin_ permissions on the repository, so you should now have access to all the settings, the repository name, description, etc.

**Comment by jenna-jordan** [comment]
Got it, thank you!
