### ISSUE TITLE
Final app error when you remove all the countries

### ISSUE THREAD

**Issue by sstevens2** [carpentries-incubator/python-interactive-data-visualizations#10]
When you remove all the countries (if you want to search for specific countries to add) it gives the following error.

![Screen Shot 2021-12-15 at 2 23 27 PM](https://user-images.githubusercontent.com/5558419/146259742-f64f287a-cbbd-424a-a296-82bcacaa2811.png)

Maybe we could add a little defensive programming exercise to the end to find this issue and create a fix for it?

**Comment by jenna-jordan** [comment]
Just to clarify, when you say "remove all the countries", do you mean clicking the "x" in the countries multi-select widget in the app, or do you mean making a change in the app.py file? When I go to my example app and deselect all countries, I just get an empty plot, not an error message.

**Comment by sstevens2** [comment]
I'll close this since it was caused by my putting the code in the wrong order.
