### ISSUE TITLE
Expanding the introduction to explain the value of interactivity?

### ISSUE THREAD

**Issue by LozRiviera** [carpentries-incubator/python-interactive-data-visualizations#3]
I think this workshop would be a really importmant one for many researchers, and would like to help.

Maybe you would consider expanding the intro slightly, or making this the first episode (like describing version control in the Git workshop: https://swcarpentry.github.io/git-novice/01-basics/index.html ) 

The points that might be worth making include (with illustrations if needed):

	- Humans benefit from visual representation of data to see patterns
	- Big and complex data will often have many possible ways to present it.
	- To produce a figure you can use many visual dimensions (x-y-z position / colour / symbols / etc)
	- However, each figure is a story you have chosen to tell with the data. 
	- Modern data sets are often too dense to visualize without making a lot of these chocies.
	- Interactivity gives the reader/user a chance to explore the data in ways a static plot does not.

A figure describing the steps that you have nicely laid out in the episodes of the workshop might also help:

	- Data processing and cleaning.  
	- Separating out variables of interest.
	- Visualizing the central data 
	- Identifying variables you may want to explore
	- Converting choices in visualization to widgets
	- Hosting a plot as an app

I am happy to try drafting this intro if you feel it would be helpful?

**Comment by jenna-jordan** [comment]
That sounds like an excellent idea! The lesson could certainly benefit from an introduction that provides the context of why researchers might want to learn these skills. I really like the points that you laid out - if you would like to take a crack at drafting the intro episode, please feel free. I think this would be good as it's own episode - I can shift the numbering of the other episodes to reflect a new episode 1 after integrating your pull request.

**Comment by LozRiviera** [comment]
I am happy to have a go.  I will try to work up a simple flowchart figure as well if it seems to add anything.

**Comment by jenna-jordan** [comment]
New first episode has been added via pull request and then edited!
